---
- name: "upgrade package"
  become: true
  apt:
    upgrade: "yes"

- name: "installing dependencies"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "installing pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present