---
- name: Starting PM2
  shell: |
    cp /home/backend.tar.gz /home/ubuntu/backend.tar.gz
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    mv home/circleci/project/backend .
    cd backend
    npm install -g npm@latest
    npm install -g webpack-dev-server
    npm install
    npm run build
    pm2 start npm --name backend -- start