---
- name: Copy backend files
  become: true
  copy:
    src: /home/backend.tar.gz
    dest: /home/ubuntu/backend.tar.gz

- name: Starting PM2
  shell: |
    cd /home/ubuntu/
    tar xzvf backend.tar.gz
    cp home/circleci/project/backend .
    cd backend
    npm install
    npm run build
    pm2 start npm --name backend -- start